### PR TITLE
Return empty recs for unsupported language

### PR DESCRIPTION
**Pull request by eu9ene**
# Goal

Fix a bug when related recommendations are displayed for a non-English item

## Jira

[ticket](https://getpocket.atlassian.net/browse/TDP-327)

## Implementation Decisions

@mmiermans @bassrock Will apollo provide `language` field to recAPI as a part of federated key if it is not present in the client request? I assume yes.
[edit]: it seems apollo is unhappy with this. any ideas on how to work around and pull language?

@anthony-liddle FYI

### CODE REVIEW

**Comment by bassrock** [comment]
@eu9ene For your use case I think you need to use computedFields to resolve it https://www.apollographql.com/docs/federation/entities-advanced#contributing-computed-entity-fields

So in your case _I think_ you would make relatedAfterArticle require `lang` (or whatever the field is on the Item object). then your resolver would get that field passed to it.

Summoning @kschelonka our resident resolver expert.

**Comment by eu9ene** [comment]
> @eu9ene For your use case I think you need to use computedFields to resolve it https://www.apollographql.com/docs/federation/entities-advanced#contributing-computed-entity-fields
> 
> So in your case _I think_ you would make relatedAfterArticle require `lang` (or whatever the field is on the Item object). then your resolver would get that field passed to it.
> 
> Summoning @kschelonka our resident resolver expert.

I'm curious what's the difference between `Item` and `SyndicatedArticle`. For `SyndicatedArticle` I just added `publisherUrl originalItemId` as a part of key and it worked. `language` filed from `Item` in `parser` subgraph looks similar to `publisherUrl` field in the `SyndicatedArticle` in `syndication` subgraph. The only difference is that it's optional.

**Comment by bassrock** [comment]
@eu9ene that resolvable piece is key, that is saying that Item is resolvable from your subgraph so federation does not pass those values through. You need it to not be resolvable so that Federation knows you require the data.

**Comment by eu9ene** [comment]
> @eu9ene that resolvable piece is key, that is saying that Item is resolvable from your subgraph so federation does not pass those values through. You need it to not be resolvable so that Federation knows you require the data.

I tried this in my last commit and it now generates:

```
type Item @key(fields: "itemId language", resolvable: false) {
  itemId: String!
  language: String
```

However, apollo still complains with:

```
INVALID_FIELD_SHARING
Non-shareable field "Item.language" is resolved from multiple subgraphs: it is resolved from subgraphs "parser" and "recommendation-api" and defined as non-shareable in subgraph "parser"
```

**Comment by bassrock** [comment]
@eu9ene yea this makes sense, tbh im surprised your publisherURL on SyndicatedArticle works, i think you need to do a computed field instead https://www.apollographql.com/docs/federation/entities-advanced#contributing-computed-entity-fields

**Comment by bassrock** [comment]
Happy to pair live on this next week

**Comment by eu9ene** [comment]
> @eu9ene yea this makes sense, tbh im surprised your publisherURL on SyndicatedArticle works, i think you need to do a computed field instead https://www.apollographql.com/docs/federation/entities-advanced#contributing-computed-entity-fields

I managed to generate a similar schema and validation passes for Item, but doesn't pass for SyndicatedArticle for some reason
```
SATISFIABILITY_ERROR

The following supergraph API query: { userById(id: "<any id>") { searchSavedItems( term: "A string value" filter: {} sort: {sortBy: CREATED_AT} pagination: {} ) { edges { node { savedItem { suggestedTags { savedItems( filter: {} sort: {sortBy: CREATED_AT, sortOrder: ASC} pagination: {} ) { edges { node { item { ... on Item { syndicatedArticle { relatedRightRail(count: 0) { ... } } } } } } } } } } } } } } cannot be satisfied by the subgraphs because: - from subgraph "syndication": cannot find field "SyndicatedArticle.relatedRightRail". - from subgraph "curated-corpus": cannot find field "SyndicatedArticle.relatedRightRail". - from subgraph "recommendation-api": cannot satisfy @require conditions on field "SyndicatedArticle.relatedRightRail".
```

I guess I'll just roll it back to use keys for now

**Review by mmiermans — APPROVED** [review]
:+1: lgtm

**Pull request merged**
