### PR TITLE
Add support of hasUserModel Unleash strategy

### PR DESCRIPTION
**Pull request by eu9ene**
# Goal

Being able to enroll in an experiment only users that are supported by the model

- [x] tested on dev feature flags + recAPI

Tickets:
*[ Link to JIRA tickets](https://getpocket.atlassian.net/browse/DIS-756)

## Implementation Decisions

Use the existing `hasUserModel` strategy that was developed for recit. It works well here, the only downside that it says recit in property name.

### CODE REVIEW

**Comment by chidamnat** [comment]
how do I test this out ?

**Comment by eu9ene** [comment]
> how do I test this out ?

I tested it using [dev featureflags ](https://featureflags.getpocket.dev/projects/default/features/temp.web.recommendation-api.home.hybrid_cf_test) and queries in dev apollo graph like: [this](https://studio.apollographql.com/graph/pocket-client-api/variant/development/explorer?explorerURLState=N4IgJg9gxgrgtgUwHYBcQC4QEcYIE4CeABABISIA2AhiggDICWSCMADkcADpJFEAW5BAGVqtRszYduvXgGdRCWVJ4zefBFTAUmCaaqKyYAI3WbtzParwIo5REjA0GEJACUNslwBUCrXStU4CGtxAGsOIhg8CiJaAA8UIgBfSxlrWzh7RxRnJCUuAP1bPFYYWQBJWjhlfX0GMFTVFMKrDxca2pkkKkRG-RRff07kvuamvWbmkAAaEAA3KjwGKiMKRQwQAt5OEFtUBASd9A7tkCpWVgA5Ht0MIh2EOYBzZAId6dSHpDmGPBd7FBHe5nCisPhUd6fEBlfDlBp3HYAVgAHAB2ACCVCeiIAzGAACyohAAJi8RmJADYcawcQgAAwAcVYADFkV4vGBkcSAIwIRG85FUULIgBm3XxEvRAE4EHBylKRVBEXSSEYKfAwMSoJDCjtZIpZLk4UCdtziTidaodqw-n48DlFECtvodhRoFQ1iaQMgALQAYXRlpdIHSlQAqvq8AAFP4ihieu7O2o7GF4ACyEDACAosiBAG0dnwCEYlmAAPpQEU7AC6o1SYxGSCSMxApizeFkGy4IHRMBQAiWAC8nC4jjsAEIaax4IgIAgAKTpCAAGuiGAB5BjzgDSADVuQBFBh0P3zvhGBlQDdboRhwflbmXBjlCpwFCsABafvKFPKFHHdBpl4zJhuUSB0gAdHO86sFAOJpte85IB%2By6uAA7uSlx4ChB4wAAmsSUooOUDBoQweHLruoTlAAVhAywkK4dJQCQaYUsufpSlAdDEpcshUAA6ruMBgH63J8FADKhDAH7EruzEMlKNFUHJdJ0HAlxzEYu5oXMJFkYJzJ0rREBxJcNFPNyaYACJpoOaYWWpp5rCQa7rjRACixLrtZYZoXZeH4j5B4VEglzcnhz6-jRoQ4pcXh2Q5oTHqeaFQHAu4oFQlHETRrDMUgu4UCe84UEYGlzB%2BDJUcuxIUNRdEMPFTw4geAnMmFXiXKElzWVoaYUK4DAOXhg5QNZlwUGmHlgGhrg0XwYa7gyB74g5zIUPFG3rgyzJ4DtH74V4B50pcHkeYiH4Cdy87rgJH40fF47lHhNEftyRgCQeBB4QQL5gfOWnVfeeVGH%2B85Rl4Hm7iKu67pcIHPhUFAQ1DMNhsy87Ml4YYULuXhCPOYAlWV7WsEY36-kg458GAcBxHMYAWYiB4MmAKB4QJObqZpRhCP9cBgNyglHu5HlxDZoT2dZB5ob1HlOaV5WaVVNXEkLIvXuUcQfhNSB3Qe3mroOD1PMSB5eKVlwCZcYYOeOa2hFLaYY6EAk0cyTVwGGEuuYOeF0h5P33QwD1hj9g7osSNlpjiKFgAJrhwMiOJ3RQfppnAq36eRhEwHBmUofOIoqbuiImRux0S146IoJcWfch%2BcB4TieFeNiutQBHZvrl4UC8XAzJwGmDJ%2BTnFHjqwtX1SZiLyxLfpkRPGEMhQNEUa45PEoiIrlcyKAfvzv7-nMBEoBQonjnHAmVARcSfgJyrj8u44r2vG9bzv2WXLvg90tlH4KC0XylAQqxVTwSRIOOfiNtaary0hQKUsFuRSgKruQcYBqoNRAWAkUB4ILMgPGmIQ45uRgDDFGD8YBXAUApAJChZYKSMLwAJNMB4sBSkHAwXicxtxRhoigzQMAfQHE4XgA81kRRxAEjyOI444hxDAC-J4aFERgnXMSEUF04g0V3HwdSeiKAkEHDiGWAloHzmsmWPC24SCXHHGmKBcwIA0QlHSLAg51zomZKEEQVASAsQQARVErAkAMgYGGFAdAsB4DmPiKgaFxw0R9K4YkqJ0GsAYJ%2BVE1kPJIEHKk7cfplwIFRK5coUY6RxClPOBADAKTMmsrIbcrBXBCEHCuCAZt0SyF2uULANN8R0F3E8VgUohAIHunhEszI6BljiMyCA1EfHLjTD6QcqIywMjwEMqUfo8B0CgLucoVAfTcj9A0tM3JCZGG5DAGUqJEQQApGmZEg4UB8IQKwA8Y0CCuA8j7KA85xzzlWaEKMVAwzrgPOcREu4-RyK8B%2BdcPsjBUA8lQbkAkPIoDALuNM64cTlHVlGNCxJkQeReDRSx1k0I60uMieFYYoBzB9HxAg65jE4lRHQCkqI8IQAIHwA8OxmxJCAA) and [this](https://studio.apollographql.com/graph/pocket-client-api/variant/development/explorer?explorerURLState=N4IgJg9gxgrgtgUwHYBcQC4QEcYIE4CeABAKpIA2CAhgM4AWAgjTQJYDmSiqNAFACRQIqBAA8U6UhWr0AwkJSiUAQgCURYAB0kRIjCm1Gzdp2Qpeg4WIkD5itZu06itVhy5n1Wp05fGEYL28iJCpEQO8AByoCcggqAMdvADcqPBYqVHCiAF9A3KRskAAaEBS0qgAjShoMEAcdDRALBTFGiXqnRqoIiIA5UIQ2okaEJLZkAkairJGkJJY8IXchrvIIuiopmZAYGnwASQCMYZAAVgAOAHYGKjZTgGYwABZLhAAmABUKt4A2e4j7ggAAwAcQiADFzh8PmBzm8AIwIU6I85UADW5wAZiEnriGABOBBwfb4zFQU5AgASFR%2B8DAbygW0SJz2RiEhxWIHhb3uTO8jQiiwi%2BBQLAQNCGHX5IFiUColE5yAAtDIGHygo08AgoPsUCQ9ngAAqLTEsBXHKUanYGgCyEDACHIEuOAG1GnQCBU0mAAPpQTGNAC6WR0%2BW8YZyWkKJTo1AdeBqmE0IAYMBQdAgaQAXlRRUI2o0AELULV4IgIAgAKSBCAAGgwWAB5FiVgDSADV4QBFFgAGRklboFRBUCbLYAyiQs-t4b0WPsaPs4CgIgAtGT7H77ciF3s2j7gkj7JBAgB0FcrESg9xtY8rSFXtYASgB3b69PCPrswACab3xKD7CwL4sD%2Btbtmi%2BwAFYQOklJPkCUCUjaPy1jI%2BJQL2by9DQVAAOrtjAYAyPCdBQCCaIwKubztohIL4lBVA0UCvZwL0SQVO2L5JEBIH4eCQLQRAIi9FBbBAo2Hw-k8vQfAw9z9pWlCUg2jZQQAom8jYACJdqcvTTiINraVAi5IL08I-vOW5QWi9yyTaWY2rZfYDi%2BUBwO2KBUOBgFQREiFIO25CKeQFRsUkq4ghBtZvOQkEwSwslsPcXZ4eC5kfL0aK9NpYDkDa5BPiwzk-lmUDab0BXqWAL5PlBdAkO2IJdk8znguQskdY2ILgngPWrr%2BHxdkCvTqeppyrnh8KVo2eGrlBsmFvsP5Qau8IVHhXYED%2BBALselYcdF07%2BRU26VoaHzqe2mLtu2vSHvOi7kBdV03SQ4KVuCHwkOQ7YfOOlZgKFm3ghEFQbluSCFnQYBwCISRgGJpxdiCYAoD%2BeFOqx7EVOO%2B1wGA8L4T2anqUZ2lok5ukvrl6ksQOYURVFMVvETJNjvsIirpVSBzV2Wn1lmC1sG8XYfEpvR4b0JDOYWbVolTNofWieFQeCSVwCQRkqVmP5AupO3zSwC0kDtWYMG8xk2vcj5gHhT5wOc9xzeQMg2nArW8aB-4wNeXmPpWmJMe2pxCU2w1GXJKC9J78KrnAP73D%2BHx3DzUDm6LklQNhcDgnANogiQL7e2BhYRLF8VCfp2nkzaMggWXb4guQUFgU%2B4NvKcmLheCKCrvjW47kkf4oOQxGFrbeG6n%2BIhrnhFKl7WhbN637ed93Pm9D3edAj5q7kNBAVQEFIUDmRlKFrh0uwy3HHkPiV7wvigXtlmYDRQlx%2Bn5iXannhPpewsDAD8KA4Jeg-hgFmeEhZehIDADAccEJKRdh%2BOOJ47Yny1mno2B0XZyCtiwAQXsCAsCnHbOcAg%2BISDvDRDIBMzZ4RZiSIWNEJByIQDYI2WslZ9KtjYFBFA5xzgRFOD%2BeEOokAIHxEgdSgjDRgyeHgEEbAGCYUpEkdSeA0R0HxDQN4WZ-JZh%2BMhOAEQkgfHOFABAlwuyUUxIaDRdBexJDwPCe4%2BI8DnFOC%2BLAlxTgiDYCgLs457h4SgB8cxrYIhwDoDaVcEAIDwjgHAaWlJxIRO0rWFgho6A0CQCCfY05OKpJ9HhGQSpzgghoCCXoMgSAYXuDQfE8JGztiSCgJAlwCAQNXOwoE9wPg%2BjRE%2BH0lIDYVCVEkSsKB2w-hkJcfEPoUAiHtoIPCuYYCFhgOcFgWZKRoggG8JAtN2x4CzOBH4lxDSNnhL2BeYkRokG0vcPAcB4QEDeP4kQlYZBQSQE%2BQs3xIT7BkKnH0tYEynCgpcSscA4pwCwL0ZWVwETBSoF2CojYsxsHBGidG9x4QMEbPcJ4XZGiFGyEAA)

**Comment by chidamnat** [comment]
> > how do I test this out ?
> 
> I tested it using [dev featureflags ](https://featureflags.getpocket.dev/projects/default/features/temp.web.recommendation-api.home.hybrid_cf_test) and queries in dev apollo graph like: [this](https://studio.apollographql.com/graph/pocket-client-api/variant/development/explorer?explorerURLState=N4IgJg9gxgrgtgUwHYBcQC4QEcYIE4CeABABISIA2AhiggDICWSCMADkcADpJFEAW5BAGVqtRszYduvXgGdRCWVJ4zefBFTAUmCaaqKyYAI3WbtzParwIo5REjA0GEJACUNslwBUCrXStU4CGtxAGsOIhg8CiJaAA8UIgBfSxlrWzh7RxRnJCUuAP1bPFYYWQBJWjhlfX0GMFTVFMKrDxca2pkkKkRG-RRff07kvuamvWbmkAAaEAA3KjwGKiMKRQwQAt5OEFtUBASd9A7tkCpWVgA5Ht0MIh2EOYBzZAId6dSHpDmGPBd7FBHe5nCisPhUd6fEBlfDlBp3HYAVgAHAB2ACCVCeiIAzGAACyohAAJi8RmJADYcawcQgAAwAcVYADFkV4vGBkcSAIwIRG85FUULIgBm3XxEvRAE4EHBylKRVBEXSSEYKfAwMSoJDCjtZIpZLk4UCdtziTidaodqw-n48DlFECtvodhRoFQ1iaQMgALQAYXRlpdIHSlQAqvq8AAFP4ihieu7O2o7GF4ACyEDACAosiBAG0dnwCEYlmAAPpQEU7AC6o1SYxGSCSMxApizeFkGy4IHRMBQAiWAC8nC4jjsAEIaax4IgIAgAKTpCAAGuiGAB5BjzgDSADVuQBFBh0P3zvhGBlQDdboRhwflbmXBjlCpwFCsABafvKFPKFHHdBpl4zJhuUSB0gAdHO86sFAOJpte85IB%2By6uAA7uSlx4ChB4wAAmsSUooOUDBoQweHLruoTlAAVhAywkK4dJQCQaYUsufpSlAdDEpcshUAA6ruMBgH63J8FADKhDAH7EruzEMlKNFUHJdJ0HAlxzEYu5oXMJFkYJzJ0rREBxJcNFPNyaYACJpoOaYWWpp5rCQa7rjRACixLrtZYZoXZeH4j5B4VEglzcnhz6-jRoQ4pcXh2Q5oTHqeaFQHAu4oFQlHETRrDMUgu4UCe84UEYGlzB%2BDJUcuxIUNRdEMPFTw4geAnMmFXiXKElzWVoaYUK4DAOXhg5QNZlwUGmHlgGhrg0XwYa7gyB74g5zIUPFG3rgyzJ4DtH74V4B50pcHkeYiH4Cdy87rgJH40fF47lHhNEftyRgCQeBB4QQL5gfOWnVfeeVGH%2B85Rl4Hm7iKu67pcIHPhUFAQ1DMNhsy87Ml4YYULuXhCPOYAlWV7WsEY36-kg458GAcBxHMYAWYiB4MmAKB4QJObqZpRhCP9cBgNyglHu5HlxDZoT2dZB5ob1HlOaV5WaVVNXEkLIvXuUcQfhNSB3Qe3mroOD1PMSB5eKVlwCZcYYOeOa2hFLaYY6EAk0cyTVwGGEuuYOeF0h5P33QwD1hj9g7osSNlpjiKFgAJrhwMiOJ3RQfppnAq36eRhEwHBmUofOIoqbuiImRux0S146IoJcWfch%2BcB4TieFeNiutQBHZvrl4UC8XAzJwGmDJ%2BTnFHjqwtX1SZiLyxLfpkRPGEMhQNEUa45PEoiIrlcyKAfvzv7-nMBEoBQonjnHAmVARcSfgJyrj8u44r2vG9bzv2WXLvg90tlH4KC0XylAQqxVTwSRIOOfiNtaary0hQKUsFuRSgKruQcYBqoNRAWAkUB4ILMgPGmIQ45uRgDDFGD8YBXAUApAJChZYKSMLwAJNMB4sBSkHAwXicxtxRhoigzQMAfQHE4XgA81kRRxAEjyOI444hxDAC-J4aFERgnXMSEUF04g0V3HwdSeiKAkEHDiGWAloHzmsmWPC24SCXHHGmKBcwIA0QlHSLAg51zomZKEEQVASAsQQARVErAkAMgYGGFAdAsB4DmPiKgaFxw0R9K4YkqJ0GsAYJ%2BVE1kPJIEHKk7cfplwIFRK5coUY6RxClPOBADAKTMmsrIbcrBXBCEHCuCAZt0SyF2uULANN8R0F3E8VgUohAIHunhEszI6BljiMyCA1EfHLjTD6QcqIywMjwEMqUfo8B0CgLucoVAfTcj9A0tM3JCZGG5DAGUqJEQQApGmZEg4UB8IQKwA8Y0CCuA8j7KA85xzzlWaEKMVAwzrgPOcREu4-RyK8B%2BdcPsjBUA8lQbkAkPIoDALuNM64cTlHVlGNCxJkQeReDRSx1k0I60uMieFYYoBzB9HxAg65jE4lRHQCkqI8IQAIHwA8OxmxJCAA) and [this](https://studio.apollographql.com/graph/pocket-client-api/variant/development/explorer?explorerURLState=N4IgJg9gxgrgtgUwHYBcQC4QEcYIE4CeABAKpIA2CAhgM4AWAgjTQJYDmSiqNAFACRQIqBAA8U6UhWr0AwkJSiUAQgCURYAB0kRIjCm1Gzdp2Qpeg4WIkD5itZu06itVhy5n1Wp05fGEYL28iJCpEQO8AByoCcggqAMdvADcqPBYqVHCiAF9A3KRskAAaEBS0qgAjShoMEAcdDRALBTFGiXqnRqoIiIA5UIQ2okaEJLZkAkairJGkJJY8IXchrvIIuiopmZAYGnwASQCMYZAAVgAOAHYGKjZTgGYwABZLhAAmABUKt4A2e4j7ggAAwAcQiADFzh8PmBzm8AIwIU6I85UADW5wAZiEnriGABOBBwfb4zFQU5AgASFR%2B8DAbygW0SJz2RiEhxWIHhb3uTO8jQiiwi%2BBQLAQNCGHX5IFiUColE5yAAtDIGHygo08AgoPsUCQ9ngAAqLTEsBXHKUanYGgCyEDACHIEuOAG1GnQCBU0mAAPpQTGNAC6WR0%2BW8YZyWkKJTo1AdeBqmE0IAYMBQdAgaQAXlRRUI2o0AELULV4IgIAgAKSBCAAGgwWAB5FiVgDSADV4QBFFgAGRklboFRBUCbLYAyiQs-t4b0WPsaPs4CgIgAtGT7H77ciF3s2j7gkj7JBAgB0FcrESg9xtY8rSFXtYASgB3b69PCPrswACab3xKD7CwL4sD%2Btbtmi%2BwAFYQOklJPkCUCUjaPy1jI%2BJQL2by9DQVAAOrtjAYAyPCdBQCCaIwKubztohIL4lBVA0UCvZwL0SQVO2L5JEBIH4eCQLQRAIi9FBbBAo2Hw-k8vQfAw9z9pWlCUg2jZQQAom8jYACJdqcvTTiINraVAi5IL08I-vOW5QWi9yyTaWY2rZfYDi%2BUBwO2KBUOBgFQREiFIO25CKeQFRsUkq4ghBtZvOQkEwSwslsPcXZ4eC5kfL0aK9NpYDkDa5BPiwzk-lmUDab0BXqWAL5PlBdAkO2IJdk8znguQskdY2ILgngPWrr%2BHxdkCvTqeppyrnh8KVo2eGrlBsmFvsP5Qau8IVHhXYED%2BBALselYcdF07%2BRU26VoaHzqe2mLtu2vSHvOi7kBdV03SQ4KVuCHwkOQ7YfOOlZgKFm3ghEFQbluSCFnQYBwCISRgGJpxdiCYAoD%2BeFOqx7EVOO%2B1wGA8L4T2anqUZ2lok5ukvrl6ksQOYURVFMVvETJNjvsIirpVSBzV2Wn1lmC1sG8XYfEpvR4b0JDOYWbVolTNofWieFQeCSVwCQRkqVmP5AupO3zSwC0kDtWYMG8xk2vcj5gHhT5wOc9xzeQMg2nArW8aB-4wNeXmPpWmJMe2pxCU2w1GXJKC9J78KrnAP73D%2BHx3DzUDm6LklQNhcDgnANogiQL7e2BhYRLF8VCfp2nkzaMggWXb4guQUFgU%2B4NvKcmLheCKCrvjW47kkf4oOQxGFrbeG6n%2BIhrnhFKl7WhbN637ed93Pm9D3edAj5q7kNBAVQEFIUDmRlKFrh0uwy3HHkPiV7wvigXtlmYDRQlx%2Bn5iXannhPpewsDAD8KA4Jeg-hgFmeEhZehIDADAccEJKRdh%2BOOJ47Yny1mno2B0XZyCtiwAQXsCAsCnHbOcAg%2BISDvDRDIBMzZ4RZiSIWNEJByIQDYI2WslZ9KtjYFBFA5xzgRFOD%2BeEOokAIHxEgdSgjDRgyeHgEEbAGCYUpEkdSeA0R0HxDQN4WZ-JZh%2BMhOAEQkgfHOFABAlwuyUUxIaDRdBexJDwPCe4%2BI8DnFOC%2BLAlxTgiDYCgLs457h4SgB8cxrYIhwDoDaVcEAIDwjgHAaWlJxIRO0rWFgho6A0CQCCfY05OKpJ9HhGQSpzgghoCCXoMgSAYXuDQfE8JGztiSCgJAlwCAQNXOwoE9wPg%2BjRE%2BH0lIDYVCVEkSsKB2w-hkJcfEPoUAiHtoIPCuYYCFhgOcFgWZKRoggG8JAtN2x4CzOBH4lxDSNnhL2BeYkRokG0vcPAcB4QEDeP4kQlYZBQSQE%2BQs3xIT7BkKnH0tYEynCgpcSscA4pwCwL0ZWVwETBSoF2CojYsxsHBGidG9x4QMEbPcJ4XZGiFGyEAA)

Thanks. For the second query for Unleash, I faced an error (FYI pls)
```
{
  "errors": [
    {
      "message": "Could not validate User: jwt expired",
      "extensions": {
        "code": "UNAUTHENTICATED",
        "stacktrace": [
          "AuthenticationError: Could not validate User: jwt expired",
          "    at new CustomGraphQLError (/usr/src/app/node_modules/@pocket-tools/apollo-utils/dist/errorHandler/errorHandler.js:30:9)",
          "    at new AuthenticationError (/usr/src/app/node_modules/@pocket-tools/apollo-utils/dist/errorHandler/errorHandler.js:84:9)",
          "    at validateAndGetPocketUser (/usr/src/app/dist/jwtUtils.js:49:19)",
          "    at getAppContext (/usr/src/app/dist/server/context.js:12:76)",
          "    at contextFactory (/usr/src/app/dist/server/context.js:36:12)",
          "    at runMicrotasks (<anonymous>)",
          "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
          "    at async ApolloServer.executeHTTPGraphQLRequest (/usr/src/app/node_modules/@apollo/server/dist/cjs/ApolloServer.js:511:32)"
        ]
      }
    }
  ]
}
```

**Review by chidamnat — APPROVED** [review]

**Comment by eu9ene** [comment]
> > > how do I test this out ?
> > 
> > 
> > I tested it using [dev featureflags ](https://featureflags.getpocket.dev/projects/default/features/temp.web.recommendation-api.home.hybrid_cf_test) and queries in dev apollo graph like: [this](https://studio.apollographql.com/graph/pocket-client-api/variant/development/explorer?explorerURLState=N4IgJg9gxgrgtgUwHYBcQC4QEcYIE4CeABABISIA2AhiggDICWSCMADkcADpJFEAW5BAGVqtRszYduvXgGdRCWVJ4zefBFTAUmCaaqKyYAI3WbtzParwIo5REjA0GEJACUNslwBUCrXStU4CGtxAGsOIhg8CiJaAA8UIgBfSxlrWzh7RxRnJCUuAP1bPFYYWQBJWjhlfX0GMFTVFMKrDxca2pkkKkRG-RRff07kvuamvWbmkAAaEAA3KjwGKiMKRQwQAt5OEFtUBASd9A7tkCpWVgA5Ht0MIh2EOYBzZAId6dSHpDmGPBd7FBHe5nCisPhUd6fEBlfDlBp3HYAVgAHAB2ACCVCeiIAzGAACyohAAJi8RmJADYcawcQgAAwAcVYADFkV4vGBkcSAIwIRG85FUULIgBm3XxEvRAE4EHBylKRVBEXSSEYKfAwMSoJDCjtZIpZLk4UCdtziTidaodqw-n48DlFECtvodhRoFQ1iaQMgALQAYXRlpdIHSlQAqvq8AAFP4ihieu7O2o7GF4ACyEDACAosiBAG0dnwCEYlmAAPpQEU7AC6o1SYxGSCSMxApizeFkGy4IHRMBQAiWAC8nC4jjsAEIaax4IgIAgAKTpCAAGuiGAB5BjzgDSADVuQBFBh0P3zvhGBlQDdboRhwflbmXBjlCpwFCsABafvKFPKFHHdBpl4zJhuUSB0gAdHO86sFAOJpte85IB%2By6uAA7uSlx4ChB4wAAmsSUooOUDBoQweHLruoTlAAVhAywkK4dJQCQaYUsufpSlAdDEpcshUAA6ruMBgH63J8FADKhDAH7EruzEMlKNFUHJdJ0HAlxzEYu5oXMJFkYJzJ0rREBxJcNFPNyaYACJpoOaYWWpp5rCQa7rjRACixLrtZYZoXZeH4j5B4VEglzcnhz6-jRoQ4pcXh2Q5oTHqeaFQHAu4oFQlHETRrDMUgu4UCe84UEYGlzB%2BDJUcuxIUNRdEMPFTw4geAnMmFXiXKElzWVoaYUK4DAOXhg5QNZlwUGmHlgGhrg0XwYa7gyB74g5zIUPFG3rgyzJ4DtH74V4B50pcHkeYiH4Cdy87rgJH40fF47lHhNEftyRgCQeBB4QQL5gfOWnVfeeVGH%2B85Rl4Hm7iKu67pcIHPhUFAQ1DMNhsy87Ml4YYULuXhCPOYAlWV7WsEY36-kg458GAcBxHMYAWYiB4MmAKB4QJObqZpRhCP9cBgNyglHu5HlxDZoT2dZB5ob1HlOaV5WaVVNXEkLIvXuUcQfhNSB3Qe3mroOD1PMSB5eKVlwCZcYYOeOa2hFLaYY6EAk0cyTVwGGEuuYOeF0h5P33QwD1hj9g7osSNlpjiKFgAJrhwMiOJ3RQfppnAq36eRhEwHBmUofOIoqbuiImRux0S146IoJcWfch%2BcB4TieFeNiutQBHZvrl4UC8XAzJwGmDJ%2BTnFHjqwtX1SZiLyxLfpkRPGEMhQNEUa45PEoiIrlcyKAfvzv7-nMBEoBQonjnHAmVARcSfgJyrj8u44r2vG9bzv2WXLvg90tlH4KC0XylAQqxVTwSRIOOfiNtaary0hQKUsFuRSgKruQcYBqoNRAWAkUB4ILMgPGmIQ45uRgDDFGD8YBXAUApAJChZYKSMLwAJNMB4sBSkHAwXicxtxRhoigzQMAfQHE4XgA81kRRxAEjyOI444hxDAC-J4aFERgnXMSEUF04g0V3HwdSeiKAkEHDiGWAloHzmsmWPC24SCXHHGmKBcwIA0QlHSLAg51zomZKEEQVASAsQQARVErAkAMgYGGFAdAsB4DmPiKgaFxw0R9K4YkqJ0GsAYJ%2BVE1kPJIEHKk7cfplwIFRK5coUY6RxClPOBADAKTMmsrIbcrBXBCEHCuCAZt0SyF2uULANN8R0F3E8VgUohAIHunhEszI6BljiMyCA1EfHLjTD6QcqIywMjwEMqUfo8B0CgLucoVAfTcj9A0tM3JCZGG5DAGUqJEQQApGmZEg4UB8IQKwA8Y0CCuA8j7KA85xzzlWaEKMVAwzrgPOcREu4-RyK8B%2BdcPsjBUA8lQbkAkPIoDALuNM64cTlHVlGNCxJkQeReDRSx1k0I60uMieFYYoBzB9HxAg65jE4lRHQCkqI8IQAIHwA8OxmxJCAA) and [this](https://studio.apollographql.com/graph/pocket-client-api/variant/development/explorer?explorerURLState=N4IgJg9gxgrgtgUwHYBcQC4QEcYIE4CeABAKpIA2CAhgM4AWAgjTQJYDmSiqNAFACRQIqBAA8U6UhWr0AwkJSiUAQgCURYAB0kRIjCm1Gzdp2Qpeg4WIkD5itZu06itVhy5n1Wp05fGEYL28iJCpEQO8AByoCcggqAMdvADcqPBYqVHCiAF9A3KRskAAaEBS0qgAjShoMEAcdDRALBTFGiXqnRqoIiIA5UIQ2okaEJLZkAkairJGkJJY8IXchrvIIuiopmZAYGnwASQCMYZAAVgAOAHYGKjZTgGYwABZLhAAmABUKt4A2e4j7ggAAwAcQiADFzh8PmBzm8AIwIU6I85UADW5wAZiEnriGABOBBwfb4zFQU5AgASFR%2B8DAbygW0SJz2RiEhxWIHhb3uTO8jQiiwi%2BBQLAQNCGHX5IFiUColE5yAAtDIGHygo08AgoPsUCQ9ngAAqLTEsBXHKUanYGgCyEDACHIEuOAG1GnQCBU0mAAPpQTGNAC6WR0%2BW8YZyWkKJTo1AdeBqmE0IAYMBQdAgaQAXlRRUI2o0AELULV4IgIAgAKSBCAAGgwWAB5FiVgDSADV4QBFFgAGRklboFRBUCbLYAyiQs-t4b0WPsaPs4CgIgAtGT7H77ciF3s2j7gkj7JBAgB0FcrESg9xtY8rSFXtYASgB3b69PCPrswACab3xKD7CwL4sD%2Btbtmi%2BwAFYQOklJPkCUCUjaPy1jI%2BJQL2by9DQVAAOrtjAYAyPCdBQCCaIwKubztohIL4lBVA0UCvZwL0SQVO2L5JEBIH4eCQLQRAIi9FBbBAo2Hw-k8vQfAw9z9pWlCUg2jZQQAom8jYACJdqcvTTiINraVAi5IL08I-vOW5QWi9yyTaWY2rZfYDi%2BUBwO2KBUOBgFQREiFIO25CKeQFRsUkq4ghBtZvOQkEwSwslsPcXZ4eC5kfL0aK9NpYDkDa5BPiwzk-lmUDab0BXqWAL5PlBdAkO2IJdk8znguQskdY2ILgngPWrr%2BHxdkCvTqeppyrnh8KVo2eGrlBsmFvsP5Qau8IVHhXYED%2BBALselYcdF07%2BRU26VoaHzqe2mLtu2vSHvOi7kBdV03SQ4KVuCHwkOQ7YfOOlZgKFm3ghEFQbluSCFnQYBwCISRgGJpxdiCYAoD%2BeFOqx7EVOO%2B1wGA8L4T2anqUZ2lok5ukvrl6ksQOYURVFMVvETJNjvsIirpVSBzV2Wn1lmC1sG8XYfEpvR4b0JDOYWbVolTNofWieFQeCSVwCQRkqVmP5AupO3zSwC0kDtWYMG8xk2vcj5gHhT5wOc9xzeQMg2nArW8aB-4wNeXmPpWmJMe2pxCU2w1GXJKC9J78KrnAP73D%2BHx3DzUDm6LklQNhcDgnANogiQL7e2BhYRLF8VCfp2nkzaMggWXb4guQUFgU%2B4NvKcmLheCKCrvjW47kkf4oOQxGFrbeG6n%2BIhrnhFKl7WhbN637ed93Pm9D3edAj5q7kNBAVQEFIUDmRlKFrh0uwy3HHkPiV7wvigXtlmYDRQlx%2Bn5iXannhPpewsDAD8KA4Jeg-hgFmeEhZehIDADAccEJKRdh%2BOOJ47Yny1mno2B0XZyCtiwAQXsCAsCnHbOcAg%2BISDvDRDIBMzZ4RZiSIWNEJByIQDYI2WslZ9KtjYFBFA5xzgRFOD%2BeEOokAIHxEgdSgjDRgyeHgEEbAGCYUpEkdSeA0R0HxDQN4WZ-JZh%2BMhOAEQkgfHOFABAlwuyUUxIaDRdBexJDwPCe4%2BI8DnFOC%2BLAlxTgiDYCgLs457h4SgB8cxrYIhwDoDaVcEAIDwjgHAaWlJxIRO0rWFgho6A0CQCCfY05OKpJ9HhGQSpzgghoCCXoMgSAYXuDQfE8JGztiSCgJAlwCAQNXOwoE9wPg%2BjRE%2BH0lIDYVCVEkSsKB2w-hkJcfEPoUAiHtoIPCuYYCFhgOcFgWZKRoggG8JAtN2x4CzOBH4lxDSNnhL2BeYkRokG0vcPAcB4QEDeP4kQlYZBQSQE%2BQs3xIT7BkKnH0tYEynCgpcSscA4pwCwL0ZWVwETBSoF2CojYsxsHBGidG9x4QMEbPcJ4XZGiFGyEAA)
> 
> Thanks. For the second query for Unleash, I faced an error (FYI pls)
> 
> ```
> {
>   "errors": [
>     {
>       "message": "Could not validate User: jwt expired",
>       "extensions": {
>         "code": "UNAUTHENTICATED",
>         "stacktrace": [
>           "AuthenticationError: Could not validate User: jwt expired",
>           "    at new CustomGraphQLError (/usr/src/app/node_modules/@pocket-tools/apollo-utils/dist/errorHandler/errorHandler.js:30:9)",
>           "    at new AuthenticationError (/usr/src/app/node_modules/@pocket-tools/apollo-utils/dist/errorHandler/errorHandler.js:84:9)",
>           "    at validateAndGetPocketUser (/usr/src/app/dist/jwtUtils.js:49:19)",
>           "    at getAppContext (/usr/src/app/dist/server/context.js:12:76)",
>           "    at contextFactory (/usr/src/app/dist/server/context.js:36:12)",
>           "    at runMicrotasks (<anonymous>)",
>           "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
>           "    at async ApolloServer.executeHTTPGraphQLRequest (/usr/src/app/node_modules/@apollo/server/dist/cjs/ApolloServer.js:511:32)"
>         ]
>       }
>     }
>   ]
> }
> ```

I need to go through the authentication procedure that is described in https://studio.apollographql.com/graph/pocket-client-api/variant/current/home. 

For the assignments query I also add such variables:
```
{
  "context": {
    "appName": "evgeny",
    "environment": "alpha",
    "userId": "<my_hashed_user_id>",
    "sessionId": "123",
    "properties": {
      "locale": "en-CA",
      "recItUserProfile": {
        "userModels": ["hybrid_cf"]
      }
    }
  }
}
```

**Review by mmiermans — APPROVED** [review]
:muscle: You've rocking it in this repo!

**Comment by eu9ene** [comment]
wrong branch

**Pull request closed without merging**
